# **Algebra**

In [1]:
import numpy as np

### _Scalars_
Individual dates Matrix Algebra. Geometrically they have one point and have dimension $0$.

In [3]:
s = np.array(7)
print(s)

7


### _Vectors_
They form a line and have dimension $1$. Matrices of one dimension, such as $m \times 1$ (vertical) or $1 \times m$ (horizontal).

In [4]:
v = np.array([2, 1, 9])
print(v)

[2 1 9]


### _Matrices_
Sequences of multiple vectors organized in two dimensions. They form a plane and have dimension $2$, denoted by $m \times n$.

In [7]:
m = np.array([[3, 4, 1], [7, 2, 8]])
print(m)

[[3 4 1]
 [7 2 8]]


## **Basic Structure**

## **Vector Algebra**

## **Matrix Algebra**

### **Flatten a matrix**